import os
import tempfile
from datetime import datetime
from fpdf import FPDF
import ezdxf
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st


class BestFitEngine:

    @staticmethod
    def best_fit_3d(measured, design):
        centroid_m = np.mean(measured, axis=0)
        centroid_d = np.mean(design, axis=0)
        m_centered = measured - centroid_m
        d_centered = design - centroid_d
        H = np.dot(m_centered.T, d_centered)
        U, S, Vt = np.linalg.svd(H)
        R = np.dot(Vt.T, U.T)
        if np.linalg.det(R) < 0:
            Vt[2, :] *= -1
            R = np.dot(Vt.T, U.T)
        T = centroid_d - np.dot(R, centroid_m)
        return R, T

    @staticmethod
    def best_fit_2d(measured, design):
        m_xy = measured[:, :2]
        d_xy = design[:, :2]
        centroid_m = np.mean(m_xy, axis=0)
        centroid_d = np.mean(d_xy, axis=0)
        m_centered = m_xy - centroid_m
        d_centered = d_xy - centroid_d
        H = np.dot(m_centered.T, d_centered)
        U, S, Vt = np.linalg.svd(H)
        R_2d = np.dot(Vt.T, U.T)
        if np.linalg.det(R_2d) < 0:
            Vt[1, :] *= -1
            R_2d = np.dot(Vt.T, U.T)
        T_2d = centroid_d - np.dot(R_2d, centroid_m)
        R = np.eye(3)
        R[:2, :2] = R_2d
        T = np.zeros(3)
        T[:2] = T_2d
        T[2] = np.mean(design[:, 2]) - np.mean(measured[:, 2])
        return R, T

    @staticmethod
    def calculate_error(df_after, df_target):
        err = df_after.sub(df_target, fill_value=0)
        err.columns = ["Delta E", "Delta N", "Delta El"]
        err["Total_Error"] = np.sqrt(
            err["Delta E"] ** 2 + err["Delta N"] ** 2 + err["Delta El"] ** 2
        )
        return err


# PDF Report Generator
class PDFReport(FPDF):

    def header(self):
        self.set_font("helvetica", "B", 14)
        self.cell(
            0,
            10,
            "2D/3D Multi-Station BestFit & CAD Conversion Report",
            0,
            1,
            "C",
        )
        self.set_font("helvetica", "I", 9)
        self.cell(
            0,
            5,
            "Generated by Ng Yit Fung - BestFit & DXF/SCR Converter Pro",
            0,
            1,
            "C",
        )
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        current_date_full = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.cell(
            0,
            10,
            f"Page {self.page_no()} | Report Date & Time: {current_date_full}",
            0,
            0,
            "C",
        )


def generate_pdf_report(df_final, df_err):
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("helvetica", "", 10)

    # 获取当前生成日期和时间
    current_date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Summary Section
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "1. Executive Summary", 0, 1, "L")
    pdf.set_font("helvetica", "", 10)
    pdf.cell(
        0, 6, f"Report Generation Date & Time: {current_date_str}", 0, 1, "L"
    )
    pdf.cell(
        0, 6, f"Total Processed Points in Final Result: {len(df_final)}", 0, 1, "L"
    )
    pdf.ln(4)

    # Final Results Table
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "2. Final Coordinates Results", 0, 1, "L")
    pdf.set_font("helvetica", "B", 9)
    pdf.set_fill_color(220, 220, 220)
    pdf.cell(50, 7, "Point ID", 1, 0, "C", True)
    pdf.cell(45, 7, "X / E", 1, 0, "C", True)
    pdf.cell(45, 7, "Y / N", 1, 0, "C", True)
    pdf.cell(45, 7, "Z / EL", 1, 1, "C", True)

    pdf.set_font("helvetica", "", 9)
    for idx, row in df_final.iterrows():
        pdf.cell(50, 6, str(idx), 1, 0, "C")
        pdf.cell(45, 6, f"{float(row['X']):.4f}", 1, 0, "C")
        pdf.cell(45, 6, f"{float(row['Y']):.4f}", 1, 0, "C")
        pdf.cell(45, 6, f"{float(row['Z']):.4f}", 1, 1, "C")

    pdf.ln(6)

    # Deviation Analysis Table (if exists)
    if df_err is not None and not df_err.empty:
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 8, "3. Deviation Analysis Report", 0, 1, "L")
        pdf.set_font("helvetica", "B", 9)
        pdf.cell(40, 7, "Point ID", 1, 0, "C", True)
        pdf.cell(35, 7, "Delta E", 1, 0, "C", True)
        pdf.cell(35, 7, "Delta N", 1, 0, "C", True)
        pdf.cell(35, 7, "Delta El", 1, 0, "C", True)
        pdf.cell(40, 7, "Total Error", 1, 1, "C", True)

        pdf.set_font("helvetica", "", 9)
        for idx, row in df_err.iterrows():
            pdf.cell(40, 6, str(idx), 1, 0, "C")
            pdf.cell(35, 6, f"{float(row['Delta E']):.4f}", 1, 0, "C")
            pdf.cell(35, 6, f"{float(row['Delta N']):.4f}", 1, 0, "C")
            pdf.cell(35, 6, f"{float(row['Delta El']):.4f}", 1, 0, "C")
            pdf.cell(40, 6, f"{float(row['Total_Error']):.4f}", 1, 1, "C")

    return bytes(pdf.output())


# CAD Color Mapping (Plotly friendly color names)
CAD_COLORS = {
    "White (Default)": ("white", 7),
    "Red": ("red", 1),
    "Yellow": ("yellow", 2),
    "Green": ("green", 3),
    "Cyan": ("cyan", 4),
    "Blue": ("blue", 5),
    "Magenta": ("magenta", 6),
    "Gray": ("gray", 8),
}

st.set_page_config(
    page_title="2D/3D Multi-Station BestFit & DXF/SCR Converter Pro",
    page_icon="🏗️",
    layout="wide",
)

st.title(
    "🏗️ 2D/3D Multi-Station BestFit & CAD DXF/SCR Converter - Made by Ng Yit"
    " Fung"
)
st.markdown(
    "Complete Raw Data editing, Station splitting, BestFit analysis, and"
    " export to CSV / DXF / SCR / PDF formats."
)

# Sidebar Uploads for CSV files
st.sidebar.header("📂 Data Uploads")
uploaded_design = st.sidebar.file_uploader(
    "Upload Design Points CSV (Optional)", type=["csv"], key="design_file"
)
uploaded_ctrl = st.sidebar.file_uploader(
    "Upload Control Points CSV (Optional)", type=["csv"], key="ctrl_file"
)
uploaded_raw = st.sidebar.file_uploader(
    "Upload Raw Data CSV (Required)", type=["csv"], key="raw_file"
)

if uploaded_raw is not None:
    try:
        # --- 初始化 Design Points 编辑器状态 ---
        if "df_design_edited" not in st.session_state:
            if uploaded_design is not None:
                df_d_init = pd.read_csv(
                    uploaded_design,
                    header=None,
                    names=["Point", "X/E", "Y/N", "Z/EL"],
                    dtype=str,
                )
            else:
                df_d_init = pd.DataFrame(
                    columns=["Point", "X/E", "Y/N", "Z/EL"]
                )
            df_d_init.index = range(1, len(df_d_init) + 1)
            st.session_state["df_design_edited"] = df_d_init

        # --- 初始化 Control Points 编辑器状态 ---
        if "df_ctrl_edited" not in st.session_state:
            if uploaded_ctrl is not None:
                df_c_init = pd.read_csv(
                    uploaded_ctrl,
                    header=None,
                    names=["Point", "X/E", "Y/N", "Z/EL"],
                    dtype=str,
                )
            else:
                df_c_init = pd.DataFrame(
                    columns=["Point", "X/E", "Y/N", "Z/EL"]
                )
            df_c_init.index = range(1, len(df_c_init) + 1)
            st.session_state["df_ctrl_edited"] = df_c_init

        # --- 初始化 Raw Data 编辑器状态 ---
        if "df_raw_edited" not in st.session_state:
            df_r_init = pd.read_csv(
                uploaded_raw,
                header=None,
                names=["Point", "X/E", "Y/N", "Z/EL"],
                dtype=str,
            )
            df_r_init.index = range(1, len(df_r_init) + 1)
            st.session_state["df_raw_edited"] = df_r_init

        unified_column_config = {
            "Point": st.column_config.TextColumn("Point", width="small"),
            "X/E": st.column_config.NumberColumn(
                "X/E", format="%.4f", width="small"
            ),
            "Y/N": st.column_config.NumberColumn(
                "Y/N", format="%.4f", width="small"
            ),
            "Z/EL": st.column_config.NumberColumn(
                "Z/EL", format="%.4f", width="small"
            ),
        }

        # --- 第一排：Design Points Editor & Control Points Editor ---
        st.markdown("---")
        col_row1_1, col_row1_2 = st.columns(2)

        with col_row1_1:
            st.subheader("📐 Design Points Editor")
            current_design = st.session_state["df_design_edited"].copy()
            current_design["Point"] = current_design["Point"].astype(str)
            for col in ["X/E", "Y/N", "Z/EL"]:
                current_design[col] = pd.to_numeric(
                    current_design[col], errors="coerce"
                )
            current_design.index = range(1, len(current_design) + 1)
            edited_design_df = st.data_editor(
                current_design,
                num_rows="dynamic",
                use_container_width=True,
                hide_index=False,
                column_config=unified_column_config,
                key="design_data_editor",
            )
            st.session_state["df_design_edited"] = edited_design_df

        with col_row1_2:
            st.subheader("🎯 Control Points Editor")
            current_ctrl = st.session_state["df_ctrl_edited"].copy()
            current_ctrl["Point"] = current_ctrl["Point"].astype(str)
            for col in ["X/E", "Y/N", "Z/EL"]:
                current_ctrl[col] = pd.to_numeric(
                    current_ctrl[col], errors="coerce"
                )
            current_ctrl.index = range(1, len(current_ctrl) + 1)
            edited_ctrl_df = st.data_editor(
                current_ctrl,
                num_rows="dynamic",
                use_container_width=True,
                hide_index=False,
                column_config=unified_column_config,
                key="ctrl_data_editor",
            )
            st.session_state["df_ctrl_edited"] = edited_ctrl_df

        df_design = None
        if not st.session_state["df_design_edited"].empty:
            temp_d = st.session_state["df_design_edited"].dropna(
                subset=["Point"]
            ).copy()
            if not temp_d.empty and "X/E" in temp_d.columns:
                temp_d["Point"] = temp_d["Point"].astype(str).str.strip()
                temp_d.set_index("Point", inplace=True)
                df_design = temp_d[["X/E", "Y/N", "Z/EL"]].astype(float).copy()
                df_design.columns = ["X", "Y", "Z"]

        df_ctrl = None
        if not st.session_state["df_ctrl_edited"].empty:
            temp_c = st.session_state["df_ctrl_edited"].dropna(
                subset=["Point"]
            ).copy()
            if not temp_c.empty and "X/E" in temp_c.columns:
                temp_c["Point"] = temp_c["Point"].astype(str).str.strip()
                temp_c.set_index("Point", inplace=True)
                df_ctrl = temp_c[["X/E", "Y/N", "Z/EL"]].astype(float).copy()
                df_ctrl.columns = ["X", "Y", "Z"]

        df_raw = st.session_state["df_raw_edited"].copy()
        df_raw["Point"] = df_raw["Point"].astype(str).str.strip()
        total_rows = len(df_raw)

        # --- 第二排：Raw Data Editor & Step 1: Split Ranges ---
        st.markdown("---")
        col_row2_1, col_row2_2 = st.columns(2)

        with col_row2_1:
            st.subheader("✏️ Raw Data Editor")
            current_raw = st.session_state["df_raw_edited"].copy()
            current_raw["Point"] = current_raw["Point"].astype(str)
            for col in ["X/E", "Y/N", "Z/EL"]:
                current_raw[col] = pd.to_numeric(
                    current_raw[col], errors="coerce"
                )
            current_raw.index = range(1, len(current_raw) + 1)
            edited_raw_df = st.data_editor(
                current_raw,
                num_rows="dynamic",
                use_container_width=True,
                hide_index=False,
                column_config=unified_column_config,
                key="raw_data_editor",
            )
            st.session_state["df_raw_edited"] = edited_raw_df
            df_raw = st.session_state["df_raw_edited"].copy()
            df_raw["Point"] = df_raw["Point"].astype(str).str.strip()
            total_rows = len(df_raw)

        with col_row2_2:
            st.subheader("🛠️ Step 1: Split Ranges")
            st.info(f"Total rows in Raw Data: **{total_rows}**.")

            num_stations = st.number_input(
                "Number of Stations", min_value=1, max_value=10, value=1, step=1
            )

            default_ranges_data = []
            chunk_size = (
                total_rows // num_stations if num_stations > 0 else total_rows
            )
            for i in range(num_stations):
                start = i * chunk_size + 1
                end = (
                    (i + 1) * chunk_size if i < num_stations - 1 else total_rows
                )
                default_ranges_data.append({
                    "Station Name": f"Station-{i+1}",
                    "Start Row": int(start),
                    "End Row": int(end),
                })

            edited_ranges_df = st.data_editor(
                pd.DataFrame(default_ranges_data),
                num_rows="fixed",
                use_container_width=True,
                hide_index=True,
                key="station_ranges_editor",
            )

        station_configs = {}
        valid_ranges = True
        for _, row in edited_ranges_df.iterrows():
            s_name = str(row["Station Name"]).strip()
            try:
                r_start, r_end = int(row["Start Row"]), int(row["End Row"])
            except ValueError:
                valid_ranges = False
                break
            if r_start > r_end or r_start < 1 or r_end > total_rows:
                valid_ranges = False
            station_configs[s_name] = (r_start - 1, r_end)

        if not valid_ranges:
            st.error(
                "⚠️ Please check station row ranges (must be valid integers"
                f" between 1 and {total_rows})."
            )
        else:
            # --- Step 2: Individual Station Fit ---
            st.markdown("---")
            st.subheader(
                "🎯 Step 2: Individual Station Fit, Deviation Analysis &"
                " Download"
            )

            if "station_fitted_dfs" not in st.session_state:
                st.session_state["station_fitted_dfs"] = {}

            tabs = st.tabs(list(station_configs.keys()))

            for idx, (s_name, (s_start, s_end)) in enumerate(
                station_configs.items()
            ):
                with tabs[idx]:
                    st.markdown(
                        f"#### Managing **{s_name}** (Rows {s_start+1} to"
                        f" {s_end})"
                    )

                    stn_raw_df = df_raw.iloc[s_start:s_end].copy()
                    stn_indexed = stn_raw_df.set_index("Point")
                    stn_calc_indexed = stn_indexed[
                        ["X/E", "Y/N", "Z/EL"]
                    ].astype(float).copy()
                    stn_calc_indexed.columns = ["X", "Y", "Z"]

                    if df_ctrl is not None and not df_ctrl.empty:
                        common_ctrl = df_ctrl.index.intersection(
                            stn_calc_indexed.index
                        )
                        col_m1, col_m2 = st.columns(2)
                        fit_method_stn = col_m1.selectbox(
                            f"Select Fit Method for {s_name}",
                            ["2D BestFit", "3D BestFit"],
                            key=f"method_{s_name}",
                        )
                        exclude_stn = col_m2.multiselect(
                            f"Exclude Control Points in {s_name}",
                            options=common_ctrl.tolist(),
                            key=f"exclude_{s_name}",
                        )

                        active_ctrl_pts = [
                            p for p in common_ctrl if p not in exclude_stn
                        ]
                        st.info(
                            f"Total common control points: {len(common_ctrl)} |"
                            f" Active for fit: {len(active_ctrl_pts)}"
                        )

                        if len(active_ctrl_pts) >= 3:
                            if st.button(
                                f"Execute {fit_method_stn} for {s_name}",
                                key=f"fit_btn_{s_name}",
                            ):
                                m_pts = stn_calc_indexed.loc[
                                    active_ctrl_pts, ["X", "Y", "Z"]
                                ].values
                                d_pts = df_ctrl.loc[
                                    active_ctrl_pts, ["X", "Y", "Z"]
                                ].values

                                if "3D" in fit_method_stn:
                                    R, T = BestFitEngine.best_fit_3d(m_pts, d_pts)
                                else:
                                    R, T = BestFitEngine.best_fit_2d(m_pts, d_pts)

                                transformed_pts = (
                                    np.dot(
                                        stn_calc_indexed[
                                            ["X", "Y", "Z"]
                                        ].values,
                                        R.T,
                                    )
                                    + T
                                )
                                df_fitted = pd.DataFrame(
                                    transformed_pts,
                                    index=stn_calc_indexed.index,
                                    columns=["X", "Y", "Z"],
                                )
                                st.session_state["station_fitted_dfs"][
                                    s_name
                                ] = df_fitted

                                df_fitted_active = df_fitted.loc[
                                    active_ctrl_pts
                                ]
                                err_stn = BestFitEngine.calculate_error(
                                    df_fitted_active,
                                    df_ctrl.loc[active_ctrl_pts],
                                )
                                st.session_state[f"err_{s_name}"] = err_stn
                                st.success(
                                    f"✅ {s_name} fitted successfully with"
                                    f" {fit_method_stn}!"
                                )
                        else:
                            st.warning(
                                "⚠️ At least 3 active common control points"
                                " are required to fit."
                            )
                    else:
                        if s_name not in st.session_state["station_fitted_dfs"]:
                            st.session_state["station_fitted_dfs"][s_name] = (
                                stn_calc_indexed[["X", "Y", "Z"]]
                            )
                        st.info(
                            "ℹ️ Control Points not provided. Using raw data"
                            " directly for this station."
                        )

                    st.markdown("---")
                    col_h1, col_h2, col_h3 = st.columns(3)

                    with col_h1:
                        st.markdown(f"**📂 Raw Data ({s_name})**")
                        st.dataframe(
                            stn_raw_df.style.format({
                                "X/E": "{:.4f}",
                                "Y/N": "{:.4f}",
                                "Z/EL": "{:.4f}",
                            }),
                            use_container_width=True,
                        )

                    with col_h2:
                        st.markdown(f"**📈 Result Preview ({s_name}_after)**")
                        if s_name in st.session_state["station_fitted_dfs"]:
                            st.dataframe(
                                st.session_state["station_fitted_dfs"][
                                    s_name
                                ].style.format("{:.4f}"),
                                use_container_width=True,
                            )
                        else:
                            st.info("Pending fit execution.")

                    with col_h3:
                        st.markdown(f"**📊 Fit Deviation Analysis**")
                        if f"err_{s_name}" in st.session_state:
                            st.dataframe(
                                st.session_state[f"err_{s_name}"].style.format({
                                    "Delta E": "{:.4f}",
                                    "Delta N": "{:.4f}",
                                    "Delta El": "{:.4f}",
                                    "Total_Error": "{:.4f}",
                                }),
                                use_container_width=True,
                            )
                        else:
                            st.info("No deviation data yet.")

                    if s_name in st.session_state["station_fitted_dfs"]:
                        stn_csv_data = (
                            st.session_state["station_fitted_dfs"][s_name]
                            .reset_index()
                            .to_csv(index=False, header=False, float_format="%.4f")
                        )
                        safe_s_name = s_name.replace(" ", "-").lower()
                        st.download_button(
                            label=f"📥 Download [{s_name}_after.CSV]",
                            data=stn_csv_data,
                            file_name=f"{safe_s_name}_after.CSV",
                            mime="text/csv",
                            key=f"dl_btn_{s_name}",
                        )

            # --- Step 3: Combine All Stations & Final BestFit ---
            st.markdown("---")
            st.subheader(
                "🚀 Step 3: Merge Stations & Final BestFit with Design Points"
            )

            if len(st.session_state["station_fitted_dfs"]) == len(
                station_configs
            ):
                combined_df = pd.concat(
                    list(st.session_state["station_fitted_dfs"].values())
                )

                if df_design is not None and not df_design.empty:
                    common_design = df_design.index.intersection(
                        combined_df.index
                    )

                    col_f1, col_f2 = st.columns(2)
                    final_method = col_f1.selectbox(
                        "Select Final Fit Method",
                        ["3D BestFit", "2D BestFit"],
                        key="f_method",
                    )
                    final_exclude = col_f2.multiselect(
                        "Exclude Design Points for Final Fit",
                        options=common_design.tolist(),
                        key="f_exclude",
                    )

                    active_design_pts = [
                        p for p in common_design if p not in final_exclude
                    ]
                    st.info(
                        f"Combined common design points: {len(common_design)} |"
                        f" Active for final fit: {len(active_design_pts)}"
                    )

                    if len(active_design_pts) >= 3:
                        if st.button(
                            "✨ Execute Final Combined Fit with Design Points",
                            type="primary",
                            use_container_width=True,
                        ):
                            m_final = combined_df.loc[
                                active_design_pts, ["X", "Y", "Z"]
                            ].values
                            d_final = df_design.loc[
                                active_design_pts, ["X", "Y", "Z"]
                            ].values

                            if "3D" in final_method:
                                R_final, T_final = BestFitEngine.best_fit_3d(
                                    m_final, d_final
                                )
                            else:
                                R_final, T_final = BestFitEngine.best_fit_2d(
                                    m_final, d_final
                                )

                            final_coords = (
                                np.dot(
                                    combined_df[["X", "Y", "Z"]].values,
                                    R_final.T,
                                )
                                + T_final
                            )
                            df_final_result = pd.DataFrame(
                                final_coords,
                                index=combined_df.index,
                                columns=["X", "Y", "Z"],
                            )
                            st.session_state["df_final_result"] = df_final_result

                            df_final_active = df_final_result.loc[
                                active_design_pts
                            ]
                            err_final = BestFitEngine.calculate_error(
                                df_final_active,
                                df_design.loc[active_design_pts],
                            )
                            st.session_state["err_final"] = err_final
                            st.success(
                                "🎉 Final Combined BestFit completed successfully!"
                            )
                    else:
                        st.warning(
                            "⚠️ At least 3 active common design points are"
                            " required."
                        )
                else:
                    st.session_state["df_final_result"] = combined_df
                    st.info(
                        "ℹ️ Design Points not provided. Merged stations are"
                        " ready for DXF/SCR preview and conversion below."
                    )

                if "df_final_result" in st.session_state:
                    st.markdown("---")
                    col_res1, col_res2 = st.columns(2)

                    with col_res1:
                        st.markdown("#### 📋 Final Result Preview")
                        st.dataframe(
                            st.session_state["df_final_result"].style.format(
                                "{:.4f}"
                            ),
                            use_container_width=True,
                        )

                    with col_res2:
                        st.markdown("#### 📊 Final Deviation Analysis")
                        if "err_final" in st.session_state:
                            st.dataframe(
                                st.session_state["err_final"].style.format({
                                    "Delta E": "{:.4f}",
                                    "Delta N": "{:.4f}",
                                    "Delta El": "{:.4f}",
                                    "Total_Error": "{:.4f}",
                                }),
                                use_container_width=True,
                            )
                        else:
                            st.info(
                                "No deviation data available (Design points not"
                                " used or not fitted)."
                            )

                    final_csv = (
                        st.session_state["df_final_result"]
                        .reset_index()
                        .to_csv(index=False, header=False, float_format="%.4f")
                    )
                    st.download_button(
                        label=(
                            "📥 Download Final Result"
                            " [station-Combine All_after BestFit.CSV]"
                        ),
                        data=final_csv,
                        file_name=(
                            "station-Combine_All_after_BestFit_Result.CSV"
                        ),
                        mime="text/csv",
                    )

                    # --- Integration of CAD / DXF & SCR Converter & Preview ---
                    st.markdown("---")
                    st.subheader(
                        "📐 CAD Layout Preview & DXF/SCR Converter (From Result)"
                    )

                    dxf_df = st.session_state[
                        "df_final_result"
                    ].reset_index()
                    dxf_df.columns = ["ID", "X", "Y", "Z"]

                    st.write("### 🛠️ Step A: Label Display Settings")
                    display_options = st.multiselect(
                        "Select what to display in the label:",
                        [
                            "ID",
                            "X Coordinate",
                            "Y Coordinate",
                            "Elevation (EL)",
                        ],
                        default=[
                            "ID",
                            "X Coordinate",
                            "Y Coordinate",
                            "Elevation (EL)",
                        ],
                        key="dxf_display_options",
                    )

                    with st.expander(
                        "⚙️ Advanced Settings (Heights, Offsets, Colors & Point"
                        " Style)",
                        expanded=False,
                    ):
                        decimal_places = st.selectbox(
                            "Decimal Places for Coordinates / EL",
                            [3, 4],
                            index=0,
                            key="dxf_dec",
                        )
                        point_color = st.selectbox(
                            "Point Symbol Color",
                            list(CAD_COLORS.keys()),
                            index=0,
                            key="dxf_pt_color",
                        )

                        st.markdown("---")
                        st.write("🎛️ **Individual Field Configurations**")
                        field_configs = {}
                        for field in [
                            "ID",
                            "X Coordinate",
                            "Y Coordinate",
                            "Elevation (EL)",
                        ]:
                            if field in display_options:
                                st.markdown(f"**📌 {field} Configuration**")
                                c1, c2, c3, c4 = st.columns(4)
                                with c1:
                                    h_val = st.number_input(
                                        f"{field} Height",
                                        value=1.0,
                                        step=0.1,
                                        key=f"h_{field}",
                                    )
                                with c2:
                                    ox_val = st.number_input(
                                        f"{field} X Offset",
                                        value=0.5,
                                        step=0.1,
                                        key=f"ox_{field}",
                                    )
                                with c3:
                                    oy_val = st.number_input(
                                        f"{field} Y Offset",
                                        value=0.5,
                                        step=0.1,
                                        key=f"oy_{field}",
                                    )
                                with c4:
                                    default_c_idx = (
                                        2 if field == "Elevation (EL)" else 0
                                    )
                                    c_val = st.selectbox(
                                        f"{field} Color",
                                        list(CAD_COLORS.keys()),
                                        index=default_c_idx,
                                        key=f"c_{field}",
                                    )

                                field_configs[field] = {
                                    "height": h_val,
                                    "offset_x": ox_val,
                                    "offset_y": oy_val,
                                    "color_name": CAD_COLORS[c_val][0],
                                    "color_idx": CAD_COLORS[c_val][1],
                                }

                        st.markdown("---")
                        st.write("📍 **CAD Point Symbol Settings**")
                        point_style_options = {
                            "Dot (.)": 0,
                            "Plus (+)": 2,
                            "X Shape": 3,
                            "Circle (○)": 32,
                            "Square (□)": 64,
                            "Circle & Cross (◎)": 34,
                        }
                        pdmode_val = st.selectbox(
                            "Point Symbol Type",
                            list(point_style_options.keys()),
                            index=5,
                            key="dxf_pdmode",
                        )
                        pdsize_val = st.number_input(
                            "Point Size", value=1.5, step=0.2, key="dxf_pdsize"
                        )

                    # Live Preview Window with Plotly
                    st.markdown("---")
                    st.markdown(
                        "### 🖥️ Live Layout Preview (Supports Mouse Roller Zoom"
                        " & Pan)"
                    )

                    valid_xs, valid_ys = [], []
                    for _, row in dxf_df.iterrows():
                        try:
                            valid_xs.append(float(row["X"]))
                            valid_ys.append(float(row["Y"]))
                        except:
                            continue

                    if valid_xs and valid_ys:
                        fig = go.Figure()

                        fig.add_trace(
                            go.Scatter(
                                x=dxf_df["X"],
                                y=dxf_df["Y"],
                                mode="markers",
                                marker=dict(
                                    color=CAD_COLORS[point_color][0],
                                    size=max(6, pdsize_val * 6),
                                    symbol="circle",
                                ),
                                text=dxf_df["ID"],
                                name="Points",
                                hoverinfo="text+x+y",
                            )
                        )

                        for idx, row in dxf_df.iterrows():
                            try:
                                x_val, y_val, z_val = (
                                    float(row["X"]),
                                    float(row["Y"]),
                                    float(row["Z"]),
                                )
                                id_val = str(row["ID"])
                                fmt = f"{{:.{decimal_places}f}}"

                                line_spacing_offset = 0.0
                                for field in display_options:
                                    if field not in field_configs:
                                        continue
                                    cfg = field_configs[field]

                                    if field == "ID":
                                        text_content = id_val
                                    elif field == "X Coordinate":
                                        text_content = f"X: {fmt.format(x_val)}"
                                    elif field == "Y Coordinate":
                                        text_content = f"Y: {fmt.format(y_val)}"
                                    else:
                                        text_content = (
                                            f"EL: {fmt.format(z_val)}"
                                        )

                                    fx = x_val + cfg["offset_x"]
                                    fy = (
                                        y_val
                                        + cfg["offset_y"]
                                        - line_spacing_offset
                                    )

                                    fig.add_annotation(
                                        x=fx,
                                        y=fy,
                                        text=text_content,
                                        showarrow=False,
                                        font=dict(
                                            color=cfg["color_name"],
                                            size=max(10, cfg["height"] * 9),
                                        ),
                                        xanchor="left",
                                        yanchor="bottom",
                                    )
                                    line_spacing_offset += cfg["height"] * 0.8
                            except:
                                continue

                        fig.update_layout(
                            paper_bgcolor="black",
                            plot_bgcolor="black",
                            xaxis_title="X Coordinate",
                            yaxis_title="Y Coordinate",
                            xaxis=dict(
                                showgrid=True,
                                gridcolor="rgba(50,50,50,0.8)",
                                zeroline=True,
                                zerolinecolor="rgba(100,100,100,0.8)",
                            ),
                            yaxis=dict(
                                showgrid=True,
                                gridcolor="rgba(50,50,50,0.8)",
                                zeroline=True,
                                zerolinecolor="rgba(100,100,100,0.8)",
                                scaleanchor="x",
                                scaleratio=1,
                            ),
                            margin=dict(l=20, r=20, t=20, b=20),
                            height=700,
                            hovermode="closest",
                        )

                        st.plotly_chart(
                            fig,
                            use_container_width=True,
                            config={"scrollZoom": True},
                        )
                    else:
                        st.warning("No coordinate values detected.")

                    # --- Generate DXF & SCR Files ---
                    doc = ezdxf.new(dxfversion="R2010")
                    msp = doc.modelspace()
                    doc.header["$PDMODE"] = point_style_options[pdmode_val]
                    doc.header["$PDSIZE"] = pdsize_val

                    scr_lines = [
                        "ucs W",
                        "Osnapcoord 1",
                    ]

                    for idx, row in dxf_df.iterrows():
                        try:
                            x_val, y_val, z_val = (
                                float(row["X"]),
                                float(row["Y"]),
                                float(row["Z"]),
                            )
                            id_val = str(row["ID"])
                            fmt = f"{{:.{decimal_places}f}}"

                            msp.add_point(
                                (x_val, y_val, z_val),
                                dxfattribs={
                                    "color": CAD_COLORS[point_color][1]
                                },
                            )

                            scr_lines.append("SPHERE")
                            scr_lines.append(
                                f"{x_val:.7f},{y_val:.7f},{z_val:.7f}"
                            )
                            scr_lines.append("D")
                            scr_lines.append(f"{pdsize_val * 0.01:.5f}")

                            line_spacing_offset = 0.0
                            for field in display_options:
                                if field not in field_configs:
                                    continue
                                cfg = field_configs[field]

                                if field == "ID":
                                    text_content = id_val
                                elif field == "X Coordinate":
                                    text_content = f"X: {fmt.format(x_val)}"
                                elif field == "Y Coordinate":
                                    text_content = f"Y: {fmt.format(y_val)}"
                                else:
                                    text_content = f"EL: {fmt.format(z_val)}"

                                fx = x_val + cfg["offset_x"]
                                fy = (
                                    y_val
                                    + cfg["offset_y"]
                                    - line_spacing_offset
                                )

                                msp.add_text(
                                    text_content,
                                    dxfattribs={
                                        "insert": (fx, fy, z_val),
                                        "height": cfg["height"],
                                        "color": cfg["color_idx"],
                                    },
                                )

                                scr_lines.append(
                                    f"-TEXT {fx:.6f},{fy:.6f},{z_val:.6f}"
                                    f" {cfg['height']:.4f} 0 {text_content}"
                                )

                                line_spacing_offset += cfg["height"] * 1.3

                        except:
                            continue

                    with tempfile.NamedTemporaryFile(
                        delete=False, suffix=".dxf"
                    ) as tmp:
                        doc.saveas(tmp.name)
                        with open(tmp.name, "rb") as f:
                            dxf_data = f.read()
                    os.unlink(tmp.name)

                    scr_content = "\n".join(scr_lines)
                    scr_data = scr_content.encode("utf-8")

                    col_dl1, col_dl2 = st.columns(2)
                    with col_dl1:
                        st.download_button(
                            "⬇️ Download Converted DXF File",
                            data=dxf_data,
                            file_name="final_station_layout.dxf",
                            mime="application/dxf",
                            use_container_width=True,
                        )
                    with col_dl2:
                        st.download_button(
                            "⬇️ Download AutoCAD Script (.SCR)",
                            data=scr_data,
                            file_name="final_station_layout.scr",
                            mime="text/plain",
                            use_container_width=True,
                        )

                    # --- 最下方：整体数据 PDF 报告下载 ---
                    st.markdown("---")
                    st.subheader("📄 Comprehensive PDF Report Export")
                    pdf_bytes = generate_pdf_report(
                        st.session_state["df_final_result"],
                        st.session_state.get("err_final", pd.DataFrame()),
                    )
                    st.download_button(
                        label="📥 Download Comprehensive PDF Report",
                        data=pdf_bytes,
                        file_name="BestFit_Comprehensive_Report.pdf",
                        mime="application/pdf",
                        use_container_width=True,
                    )
            else:
                st.info(
                    "👉 Please complete the individual steps for **all**"
                    " defined stations in Step 2 before proceeding."
                )

    except Exception as e:
        st.error(f"Processing error: {e}")
else:
    st.info(
        "👈 Please upload **Raw Data CSV** in the sidebar (or leave Design/Control"
        " files to be edited/added manually) to start."
    )
